name: dependabot-pr-merge
on:
  workflow_run:
    branches:
      - dependabot/**
    workflows:
      - code-quality-check
    types:
      - completed

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Enable auto-merge for dependabot PRs
        run: |
          gh pr review --approve "$PR_NUMBER"
          gh pr merge --auto --rebase "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          REPO: ${{ github.event.repository.full_name }}
