name: GitHub Actions Demo
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm build
      - run: npm run publish
